version: '3.5'

services:

  ldap-api:
    image: azure-ad
    container_name: azure-ad
    build:
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5001:80"
    restart: always
    networks:
      - fnet        
   
networks:
  fnet:
    driver: bridge
